export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const GET_INSTALLMENTS = "GET_INSTALLMENTS";
export const GET_INSTALLMENTS_SUCCESS = "GET_INSTALLMENTS_SUCCESS";
export const GET_INSTALLMENTS_FAIL = "GET_INSTALLMENTS_FAIL";
